spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: cloud
  jpa:
    database: POSTGRESQL
eureka:
  instance:
    hostname: ms-catalog-service.cfapps.io
    nonSecurePort: 80